'use strict';

const MIN_LENGTH_OF_FULLY_RANDOM_PASSWORD = 5;
const MAX_LENGTH_OF_FULLY_RANDOM_PASSWORD = 15;
const MIN_ASCII_CODE = 33;
const MAX_ASCII_CODE = 126;
const MAX_NUMBER_OF_WORDS_IN_HUMAN_LIKE_PASSWORD = 5;

module.exports = {
    MAX_LENGTH_OF_FULLY_RANDOM_PASSWORD,
    MIN_LENGTH_OF_FULLY_RANDOM_PASSWORD,
    MIN_ASCII_CODE,
    MAX_ASCII_CODE,
    MAX_NUMBER_OF_WORDS_IN_HUMAN_LIKE_PASSWORD
}